!obj:pylearn2.train.Train {
    dataset: &train !obj:SAheartS.load_data {
        start: 0,
        stop: 340,
    },
    model: !obj:pylearn2.models.mlp.MLP {
#	layers is a list [] that specifies the component layers to run in parallel
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'h0',
                     dim: 50,
                     irange: 0.
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 2,
                     irange: 0.
                 }
                ],
        nvis: 9,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: 0.01,
        batch_size: 10,
        monitoring_dataset:
# Dataset or dictionary
            {
                'train' : *train,
                'valid' : !obj:SAheartS.load_data {
                            start: 341,
                            stop: 400,
                          },
                'test'  : !obj:SAheartS.load_data {
                            start: 400,
                            stop: 462,
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
#                !obj:pylearn2.termination_criteria.MonitorBased {
#                    channel_name: "valid_y_misclass"
#                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 100
                }
            ]
        }
    },
#    extensions: [
#        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
#             channel_name: 'valid_y_misclass',
#             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
#        },
#    ],
    save_freq: 1
}
