Standarize and randomize order of samples in a .csv dataset with target on the first column
========================================================

For the moment only real values are allowed

```{r load_dataset}
#Se cargan los datos
fileName = "mnist_test"
fileName.csv = paste(fileName,".csv", sep="")
setwd('~/Documents/pylearn2/datasets/MNIST')
DATOS<-read.csv( paste(fileName.csv) ,header=F,dec=".",sep=",")
str(DATOS)
#check there are no NaNs in the data
all(!(is.na(DATOS)))
```


```{r scaling_data}
DATOS[,-1] <- scale(DATOS[,-1])
#replace nan with zero after scaling
DATOS <- rapply( DATOS, f=function(x) ifelse(is.nan(x),0,x), how="replace" )
str(DATOS)
```


```{r add_one_hot_column}
DATOS <- cbind(abs(DATOS[,1] -1), DATOS )


```

```{r add_classification_columns}

```


```{r randomizing_data_order}
newDATOS <- DATOS
positions <- sample(1:dim(DATOS)[1])

j=1
for (i in positions){
  newDATOS[j,] <- DATOS[i,]
  j <- j+1
}
```


```{r saving_data}

newFileName = paste(fileName, "extra", ".csv", sep="")
                
write.table(newDATOS, file = newFileName, sep = ",", eol = "\r", na = "NA", dec = ".", row.names = FALSE, col.names = TRUE)
```


