!obj:pylearn2.train.Train {
    dataset: &train !obj:higgs.load_data {
        start: 0,
        stop: 4000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'h0',
                     dim: 50,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 2,
                     irange: 0.
                 }
                ],
        nvis: 28,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: 0.01,
        batch_size: 10,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:higgs.load_data {
                            start: 4001,
                            stop: 4500
                },
                'test'  : !obj:higgs.load_data {
                            start: 4501,
                            stop: 5000
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [

#                !obj:pylearn2.termination_criteria.MonitorBased {
#                    channel_name: "valid_y_misclass"
#                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 100
                }
            ]
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
    ],
    save_freq: 1
}
