!obj:pylearn2.train.Train {
    dataset: &train !obj:csv_dataset.CSVDataset {
        start: 0,
        stop: 730,
        path: 'Concrete_DataS.csv',
        task: 'regression',
        expect_labels : True,
        expect_headers : True,
        delimiter : ';'
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'h0',
                     dim: 500,
                     irange: .05,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.Sigmoid {
                     layer_name: 'h1',
                     dim: 500,
                     irange: .05,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.LinearGaussian {
                     init_bias: !obj:pylearn2.models.mlp.mean_of_targets { 
                       dataset: *train },
                     init_beta: !obj:pylearn2.models.mlp.beta_from_targets { 
                       dataset: *train },
                     min_beta: 1.,
                     max_beta: 100.,
                     beta_lr_scale: 1.,
                     dim: 1,
                     # max_col_norm: 1.9365,
                     layer_name: 'y',
                     irange: .005
                 }
                ],
        nvis: 8,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: 0.0001,
        batch_size: 10,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:csv_dataset.CSVDataset {
                            start: 731,
                            stop: 881,
                            path: 'Concrete_DataS.csv',
                            task: 'regression',
                            expect_labels : True,
                            expect_headers : True,
                            delimiter : ';'
                          },
                'test'  : !obj:csv_dataset.CSVDataset {
                            start: 882,
                            stop: 1030,
                            path: 'Concrete_DataS.csv',
                            task: 'regression',
                            expect_labels : True,
                            expect_headers : True,
                            delimiter : ';'
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
#                !obj:pylearn2.termination_criteria.MonitorBased {
#                    channel_name: 'valid_y_mse'
#                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 100
                }
            ]
        }
    },
#    extensions: [
#        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
#             channel_name: 'valid_y_mse',
#             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
#        },
#    ],
    save_freq: 1
}
