!obj:pylearn2.train.Train {
    dataset: &train !obj:csv_dataset.CSVDataset {
        start: 0,
        stop: 730,
        path: 'Concrete_DataS.csv',
        task: 'regression',
        expect_labels : True,
        expect_headers : True,
        delimiter : ';'
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 500,
                     irange: .05,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 500,
                     irange: .05,
                     max_col_norm: 1.9365,
                 },
                 !obj:pylearn2.models.mlp.Linear {
                     layer_name: 'y',
                     dim: 1,
                     irange: 0.1
                 }
                ],
        nvis: 8,
    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        line_search_mode: 'exhaustive',
        batch_size: 10,
        conjugate: 1,
        reset_conjugate: 0,
        reset_alpha: 0,
        updates_per_batch: 1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:csv_dataset.CSVDataset {
                            start: 731,
                            stop: 881,
                            path: 'Concrete_DataS.csv',
                            task: 'regression',
                            expect_labels : True,
                            expect_headers : True,
                            delimiter : ';'
                          },
                'test'  : !obj:csv_dataset.CSVDataset {
                            start: 882,
                            stop: 1030,
                            path: 'Concrete_DataS.csv',
                            task: 'regression',
                            expect_labels : True,
                            expect_headers : True,
                            delimiter : ';'
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 100
                }
            ]
        }
    },
    
    save_freq: 1
}
